/**
 * 1.CHANGE_CATALOG_TYPE: 修改catalog的类型
 */
export const CHANGE_CATALOG_TYPE = 'CHANGE_CATALOG_TYPE'; 
export type CHANGE_CATALOG_TYPE = typeof CHANGE_CATALOG_TYPE;

/**
 * 2.RESET_CATALOG_PAGEINDEX: 重置catalog分页
 */
export const RESET_CATALOG_PAGEINDEX = 'RESET_CATALOG_PAGEINDEX';
export type RESET_CATALOG_PAGEINDEX = typeof RESET_CATALOG_PAGEINDEX;

/**
 * 3.RECORD_SELECTED_CATEGORY_ID: 记录被选中的category id
 */
export const RECORD_SELECTED_CATEGORY_ID = 'RECORD_SELECTED_CATEGORY_ID';
export type RECORD_SELECTED_CATEGORY_ID = typeof RECORD_SELECTED_CATEGORY_ID;

/**
 * 4.CATALOG_MODELS_REQUEST: 告诉UI来显示加载界面
 */
export const CATALOG_MODELS_REQUEST = 'CATALOG_MODELS_REQUEST';
export type CATALOG_MODELS_REQUEST = typeof CATALOG_MODELS_REQUEST;

/**
 * 5.CATALOG_MODELS_RECEIVE: UI会隐藏加载界面，并显示接收到的数据
 */
export const CATALOG_MODELS_RECEIVE = 'CATALOG_MODELS_RECEIVE';
export type CATALOG_MODELS_RECEIVE = typeof CATALOG_MODELS_RECEIVE;

/**
 * 5.RECORD_CATALOG_SEARCH_CONDITIONS: 记录catalog查询条件
 */
export const RECORD_CATALOG_SEARCH_CONDITIONS = 'RECORD_CATALOG_SEARCH_CONDITIONS';
export type RECORD_CATALOG_SEARCH_CONDITIONS = typeof RECORD_CATALOG_SEARCH_CONDITIONS;

/**
 * 6.RECORD_HEADER_SEARCH_CATEGORIES: 记录头部查询的分类信息
 */
export const RECORD_HEADER_SEARCH_CATEGORIES = 'RECORD_HEADER_SEARCH_CATEGORIES';
export type RECORD_HEADER_SEARCH_CATEGORIES = typeof RECORD_HEADER_SEARCH_CATEGORIES;